# head
menu:
  Home: /
  Archives: /archives
  Rss: /rss2.xml
  Podcast: /podcast.xml
  FAQ: /faq
rss: /rss2.xml
favicon: /images/logo_icon.png

# main
date_format: 'MMMM D, YYYY'
excerpt_link: READ MORE
comment_link: COMMENT BELOW
